# Generated by Django 4.1.2 on 2022-10-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('num_tel', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'db_alumno',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.IntegerField(primary_key=True, serialize=False)),
                ('asignatura', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'db_asignatura',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id_establecimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('establecimiento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'db_establecimiento',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('num_tel', models.CharField(max_length=12)),
                ('id_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRegistrApp.establecimiento')),
            ],
            options={
                'db_table': 'db_profesor',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRegistrApp.alumno')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRegistrApp.asignatura')),
                ('id_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRegistrApp.establecimiento')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRegistrApp.profesor')),
            ],
            options={
                'db_table': 'db_registro',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRegistrApp.establecimiento'),
        ),
    ]
