# Generated by Django 4.0.4 on 2022-12-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRegistrApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.IntegerField()),
                ('id_alumno', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registro',
            name='id_alumno',
        ),
    ]
